apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-query-compiler
    app: query-compiler-web
  name: query-compiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-query-compiler
      app: query-compiler-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-query-compiler
        app: query-compiler-web  
        tier: frontend
        track: stable      
    spec:
      volumes:
      - name: volumelogs
        hostPath:
          path: /mnt/logs
      containers:
      - env:
        - name: LOG_DIR
          value: /var/logs
        - name: SERVICE_PORT
          value: "8888"
        - name: HEARTBEAT
          value: "5"
        - name: CONNECTION_ATTEMPTS
          value: "2"
        - name: RETRY_DELAYS
          value: "10"
        - name: dwh_query_compiler_mq_connection_string
          value: amqp://dwh:dwh@rabbitmq:5672          
        - name: TASK_BROKER_HOST
          value: 10.50.4.110
        - name: REQUEST_QUEUE
          value: compile_tasks
        - name: RESULT_QUEUE
          value: compile_results
        - name: RESULT_CHANNEL_EXCHANGE
          value: query_compile
        - name: RESULT_CHANNEL_ROUTING_KEY
          value: result
        - name: dwh_query_compiler_data_catalog_url 
          value: "http://data-catalog:8000"
        - name: dwh_query_compiler_iam_url
          value: "http://iam:8000"          
        image: 10.50.4.110:5000/query-compiler:dev
        imagePullPolicy: Always
        name: query-compiler
        ports:
        - containerPort: 8888
        volumeMounts:
          - mountPath: /var/log/n3dwh/
            name: volumelogs            
      imagePullSecrets:
        - name: repositorycred
      hostAliases:
        - ip: 127.0.0.1        
          hostnames:
          - query-compiler.lan             

---
apiVersion: v1
kind: Service
metadata:
  name: query-compiler
  labels:
    app: query-compiler-web  
spec:
  clusterIP: None
  ports:
   - name: http
     protocol: TCP
     port: 8888
  selector:
   app: query-compiler-web  

