apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "query-compiler.fullname" . }}-configmap
  labels:
    {{- include "query-compiler.labels" . | nindent 4 }}
    {{- if ne .Values.ciEnv "" }}
    environment: {{ .Values.ciEnv }}
    {{- end }}
data:
  {{- range $key, $value := .Values.configmap }}
  dwh_query_compiler_{{ $key }}: {{ $value | quote }}
  {{- end }}