apiVersion: v1
kind: Secret
metadata:
  name: {{ template "query-compiler.fullname" . }}-secret
  labels:
    {{- include "query-compiler.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  dwh_query_compiler_{{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
type: Opaque