apiVersion: v1
kind: Secret
metadata:
  name: {{ template "query-compiler.fullname" . }}-secret
  labels:
    {{- include "query-compiler.labels" . | nindent 4 }}
data:
  dwh_query_compiler_mq_connection_string: {{ .Values.secrets.mq_connection_string }}
type: Opaque