{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "query-compiler.serviceAccountName" . }}
  labels:
    {{- include "query-compiler.labels" . | nindent 4 }}
    {{- if ne .Values.ciEnv "" }}
    environment: {{ .Values.ciEnv }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
